### ISSUE TITLE
User Story: External Links Should Open New Tab

### ISSUE THREAD

**Issue by mitchellmarshe** [theworkingmen/idb#100]
As a user, I would like for the external links to open a new tab in my browser, so that I do not accidently exit your website. 
Hint: target={_blank}

**Comment by abelhtt** [comment]
This is actually a good feature to have. It's annoying to leave the website after clicking a link. Thanks for pointing it out. 

Estimated time for the fix - 2 hours.
Assumptions - React supports opening links on a new tab. 
Actual time - ? @christian-onuogu

**Comment by christian-onuogu** [comment]
Actual time - about 20 minutes

**Comment by abelhtt** [comment]
All external links open a new tab!
