### ISSUE TITLE
User Story: Legend on Search Page

### ISSUE THREAD

**Issue by longhorn396** [theworkingmen/idb#102]
As a user, I want a better legend when searching, preferably one that doesn't have invisible text in between the options. 
![image](https://user-images.githubusercontent.com/16629308/38520782-61b29b9e-3c09-11e8-877b-61fc4a29f863.png)

**Comment by abelhtt** [comment]
We did not see that. Thank you for pointing it out.

Estimated time to fix - 30 minutes. 
Actual time - ? @christian-onuogu

**Comment by christian-onuogu** [comment]
Actual time - about 10 minutes.
