### ISSUE TITLE
Improvements to tool list on about page

### ISSUE THREAD

**Issue by cilki** [theworkingmen/idb#103]
As users, we want the tools list on the about page to have descriptions of the tools you used and links to their homepages.

**Comment by abelhtt** [comment]
We agree that the table looks ugly. We will make the tools be cards with images and descriptions. We'll make the cards clickable to the homepages. 

Estimated time - 2 hours. 
Assumption - We'll be able to get images for all the tools we use.
Actual time - ?

**Comment by abelhtt** [comment]
@smcw66

**Comment by abelhtt** [comment]
Actual time - 3 hours.
