### ISSUE TITLE
User Story: Console Errors

### ISSUE THREAD

**Issue by longhorn396** [theworkingmen/idb#104]
As a user, I want to use a website that doesn't output multiple errors to the console. 

Grid:
![image](https://user-images.githubusercontent.com/16629308/38521011-0763bb86-3c0a-11e8-839d-77022e7854d8.png)

Search: 
![image](https://user-images.githubusercontent.com/16629308/38521058-294c901a-3c0a-11e8-9e80-c22cec8a5d76.png)

**Comment by therealsamf** [comment]
![image](https://user-images.githubusercontent.com/11801943/38521344-ff7a1996-3c0a-11e8-9fc9-2c11dd63431c.png)

Also this shouldn't happen in your production javascript.

I suspect you guys didn't set process.env.NODE_ENV = 'production' when you built your app.

If you're using create-react-app, `npm run build` should fix these problems

**Comment by abelhtt** [comment]
We are actually using npm run build. When you added issues to our GitHub, it broke our build. Which is fixed now. 

We will be fixing the errors on the console. 
Estimated time - 4 hours. 
Actual time - ? @christian-onuogu

**Comment by abelhtt** [comment]
Actual time - 3 hours.
