### ISSUE TITLE
User Story: Redesign About Page

### ISSUE THREAD

**Issue by mitchellmarshe** [theworkingmen/idb#105]
As a user, I want to see information easily within the About page and any other page. The titles should pop out more. Perhaps, inverse the color scheme. Finally, the columns and rows of information should be more uniform in width.

**Comment by abelhtt** [comment]
We will do a complete redesign of the About page. We will remove the tables and add cards with pictures for sources and tools.

**Comment by abelhtt** [comment]
Estimated time - 5 hours.
Actual time - ?

**Comment by abelhtt** [comment]
Actual time was 4.5 hours.
