### ISSUE TITLE
As a user, I want a more relevant favicon.ico

### ISSUE THREAD

**Issue by therealsamf** [theworkingmen/idb#106]
Currently, the favicon is the default one that ships with create-react-app. It should be something more relevant to the site.

**Comment by abelhtt** [comment]
We've been meaning to fix that. Thanks for the reminder.

Estimated time - 1 hour.
Assumption - We can get a favicon icon that fits our website. 
Actual time - ? @christian-onuogu

**Comment by abelhtt** [comment]
Done.
