### ISSUE TITLE
Fix the thumbnail aspect ratios

### ISSUE THREAD

**Issue by cilki** [theworkingmen/idb#107]
As users, we want thumbnails to have the correct aspect ratio rather than stretch to accommodate the size of the box. It would look better to have blank space than warp the images.

**Comment by christian-onuogu** [comment]
![screenshot from 2018-04-19 17 08 19](https://user-images.githubusercontent.com/25673503/39020981-763d8c2a-43f4-11e8-910b-396424e27a17.png)

We tried a few different ways to accomplish this and feel that it looks best the way it currently is.
