### ISSUE TITLE
User Story - 1

### ISSUE THREAD

**Issue by NealFM** [theworkingmen/idb#22]
As a super user, I should be able to make changes to the repo and see those changes reflected on the website.

**Comment by abelhtt** [comment]
This requires Github integration with AWS. It is a very useful feature to add. Especially for seeing the updates in real time without manually deploying it every time.

**Comment by abelhtt** [comment]
Implementation estimate time - Should be completed in the early days of the next phase. 
@NealFM What do you think?

**Comment by NealFM** [comment]
I agree, I've been looking into some techniques to implement this, such as AWS CodeDeploy, but want to hold of doing anything on the production side until after the first phase.

**Comment by abelhtt** [comment]
This feature was added when integrated our database with our backend. 
Estimated completion time ~ 5 hours.
Our assumption of AWS RDS integration with our server was correct.
Actual completion time ~ 12 hours.
