### ISSUE TITLE
User Story - 3

### ISSUE THREAD

**Issue by traylor1** [theworkingmen/idb#24]
As a computer science student, I want to know what cities employ workers with this degree to help me narrow down my job search.

**Comment by traylor1** [comment]
Finding sources to use for this story (which companies are based in which cities) took longer than expected. I imagine this section will be among the most difficult to construct as we build our API. Manually searching, in addition to creating the base pages, took about 3.5 hours.

**Comment by abelhtt** [comment]
We now have data about majors with the highest number of graduates in a city as well as the average wage of majors for a given city. I assume this would help students get information about the relationship between cities and majors to narrow down their job search. 

Estimated Completion time - 18 hours.
Actual time ~ 22 hours. 
Our assumption of getting city and major statistics was correct. 
Data source - https://github.com/DataUSA/datausa-api/wiki
