### ISSUE TITLE
User Story - 5

### ISSUE THREAD

**Issue by NealFM** [theworkingmen/idb#26]
As a student looking for colleges, I want to be able to see on a map where the colleges are with a possible scale/rank for job opportunities on the map.

**Comment by traylor1** [comment]
This is something we can and should implement, but later. Once we get our APIs working better, we can figure out how to scrape and display maps, say from Google, and plot the pins from there. I'm estimating that this will take a while, but could be reused in ways for all models. My guess is roughly 14 hours split between two or three of us.

**Comment by abelhtt** [comment]
If we can pull data for job opportunities, it would be an awesome feature. We might try that in the next phase. Close this issue for now.
