### ISSUE TITLE
Create a UML diagram

### ISSUE THREAD

**Issue by abelhtt** [theworkingmen/idb#50]
If you know/are willing to learn how to make UML diagrams, please assign yourself.

**Comment by abelhtt** [comment]
see `[UML Basics](https://www.ibm.com/developerworks/rational/library/content/RationalEdge/sep04/bell/index.html)`
use a drawing tool (e.g. Gliffy, PlantUML, yUML)

**Comment by smcw66** [comment]
I suggest we use LucidCharts. It is intuitive to use and it free online tool.
I'll start a document of it soon

**Comment by traylor1** [comment]
This has been done for approximately three days now. I'll upload it to this repo as a pdf or image file, then close this issue.

**Comment by traylor1** [comment]
Done. For the record, I did create it with LucidCharts.
