### ISSUE TITLE
Write GitBook Book & Manual

### ISSUE THREAD

**Issue by abelhtt** [theworkingmen/idb#55]

**Comment by traylor1** [comment]
Work-in-progress. I've already added new data to our report over components we added this phase, but two more things remain:

1. Citing our sources for each data attribute
2. Rewriting our API manual

**Comment by NealFM** [comment]
Merged the changes made in Major Potential gitbook (https://theworkingmen.gitbooks.io/major-potential/content/) to the report site for grading (https://theworkingmen.gitbooks.io/report/content/). API was updated as well and can be found at https://theworkingmen.gitbooks.io/api/content/.
