### ISSUE TITLE
Cities table don't have State attribute

### ISSUE THREAD

**Issue by abelhtt** [theworkingmen/idb#70]

**Comment by NealFM** [comment]
Possible solution would be to SSH into database and use ALTER TABLE [table] ADD COLUMN [col]  PostgreSQL commands then we can use the SQLAlchemy function of update to fill in the column data since we can't directly add columns using SQLAlchemy.

**Comment by traylor1** [comment]
Yeah, that's what I was thinking. Surely there's a way to do that. Side note, I'm about to update the scripts for this now. Where should I upload it when I'm done? (I mean branch-wise)

**Comment by traylor1** [comment]
What I just pushed isn't perfect, as there's at least one city name that doesn't follow the regex I created (namely "Wayne County")

**Comment by abelhtt** [comment]
Does it show up as "Wayne County, some_state"? or just Wayne County?

**Comment by traylor1** [comment]
Just Wayne County

**Comment by abelhtt** [comment]
Done
