### ISSUE TITLE
FIX Data types in models

### ISSUE THREAD

**Issue by NealFM** [theworkingmen/idb#77]
As it stands by having everything represented as a string causes problems for sorting/ordering in the Major model since both average_wage and totat_people_in_work_force are strings. As current behavior stands the sort returns the shortest strings first in order. I.E. Given 98, 99, 100 when sorted in descending order produces 99, 98, 100. It gets worse with even longer strings of numbers. Possible suggest is to use regular expressions to parse current data and cast to appropriate types.

**Comment by NealFM** [comment]
On a side note, Precision Metal Working has several fields of data listed as "N/A", courtesy of the naive sort I notice this.

**Comment by abelhtt** [comment]
I'll look into it. Can we skip the "N/A" values in sorting?

**Comment by abelhtt** [comment]
average_wage and totat_people_in_work_force are now integers in the new database.
The N/A values are changed to -1.
